### ISSUE TITLE
在cookie中没有发现xiaoeid

### ISSUE THREAD

**Issue by lsz66** [Yxnt/xiaoet#1]
你好，我在cookie中没有发现xiaoeid，尝试过重新登录还是没有

**Comment by Yxnt** [comment]
@LSZ66 不好意思最近比较忙并且出国旅游一趟，能否提供相应截图？

**Comment by lsz66** [comment]
> @LSZ66 不好意思最近比较忙并且出国旅游一趟，能否提供相应截图？

诶，我今天再去看的时候又出现了，打扰你啦不好意思

**Comment by ghost** [comment]
![xxx](https://user-images.githubusercontent.com/19859110/49130429-d5641d80-f30e-11e8-93f0-37b3232905a3.png)
没有xiaoeid

**Comment by Yxnt** [comment]
@zhangleilei-xyz 尝试重新登陆下看看，不知道为啥小鹅通经常这样，下次可能就有了

**Comment by ghost** [comment]
> @zhangleilei-xyz 尝试重新登陆下看看，不知道为啥小鹅通经常这样，下次可能就有了

xiaoeid不是userid吧？我用抓包工具也只找到userid，找不到xiaoeid

**Comment by Yxnt** [comment]
@zhangleilei-xyz -。- xiaoeid不是userid，不知道为啥小鹅通有这毛病。。之前做调试的时候也是一会有一会没有。。

**Comment by Toddwunz** [comment]
名字被改了, 填这个tgw_l7_route就OK了

**Comment by redstoneleo** [comment]
又改了
