### ISSUE TITLE
不能搞定了

### ISSUE THREAD

**Issue by redstoneleo** [Yxnt/xiaoet#2]
Traceback (most recent call last):
  File "xiaoet.py", line 113, in <module>
    XET().download()
  File "xiaoet.py", line 65, in download
    url = data['video_hls']
TypeError: 'NoneType' object is not subscriptable

**Comment by Yxnt** [comment]
@redstoneleo 你可以debug下看看54行的hls返回什么数据

**Comment by redstoneleo** [comment]
> {"code":40004,"msg":"\u65e0\u6548\u53c2\u6570","data":null,"request_params":{"app_id":"appzDSBtscz6568","data":{"resource_id":"a_5baf68da42111_XfA8F2of","user_id":"u_5b1ef907b9f57_MR7sFj1OUS"},"use_type":"11"}}


您可以试试看
 

>    APPID = 'appzDSBtscz6568'  # APPid
>     XIAOEID = '29b254f49b8f327bd82d851eb74490e9'  # Cookie XIAOEID
>     RESOURCEID = 'p_58536d1734dc4_I3hDptgS'  # ResourceID
>     sessionid = 'eyJpdiI6ImowM094OVFcL3E4c2FKa0xyRlBKQTZnPT0iLCJ2YWx1ZSI6IjRhbDFiZWRZWUlDK1JhbGYyQUhqWDRcL3JtbDhWK0NMSm94eG5lVGcrQnZ3enB1dnlGdUxWMkxtUnBsVzBsMlpnTDFhVTJ5MmRQNGYxWE9nU3dYdFRIQT09IiwibWFjIjoiMjNlNGU4MTY5ZGI3MDJhY2ZlZGFkNDRmZmYxYmQwNmQzNjc1N2I3NDExMjRjMWJjODQxZGZiYmFhOTQzN2UwNiJ9'  # Cookie laravel_session
>

**Comment by Yxnt** [comment]
@redstoneleo 接口返回无效参数可能是小鹅通有地方更新了

**Comment by redstoneleo** [comment]
除了cookie外的headers我都加上了，但还是搞不定，我看你代码里构造的cookie好像少了点东西——没有` Hm_lvt_`之类的东西，我看到的cookie如下，但即便是加上了好像还是不行

`Cookie: XIAOEID=29b254f49b8f327bd82d851eb74490e9; Hm_lvt_32573db0e6d7780af79f38632658ed95=1536215147; Hm_lpvt_32573db0e6d7780af79f38632658ed95=1536215328; tgw_l7_route=1f4fc3a8216a1a6558ccfd82bd9a54b9; laravel_session=eyJpdiI6IlQ0Tzhndno1S3VyZzNpYVZYQU40QlE9PSIsInZhbHVlIjoia3NnUXp0d3dsejJJYXo5Yk5FWjlLQ0FVY2ZVWDhnaEFzYnBUc2I1VDdcL0Rpc29qUFo0MFlub0dyaGs4YlBRYWI2RXlTNWZFendCVjlland6V3JqazhRPT0iLCJtYWMiOiJkYjZlYTg1NGU4N2FlZmE5ZDExODkzNmJkODY1YTVmNjQxZTkwMjNjYjNjMGExM2Y4NWQ3ZmFl`

我重写的headers

 ```
       self.header = {
            'Accept': '*/*',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9',
            'Connection': 'keep-alive',
            'Content-Length': '46',
            'Content-Type': 'application/x-www-form-urlencoded',
            'Cookie': 'XIAOEID=29b254f49b8f327bd82d851eb74490e9;Hm_lvt_32573db0e6d7780af79f38632658ed95=1536215147;Hm_lpvt_32573db0e6d7780af79f38632658ed95=1536215328;tgw_l7_route=1f4fc3a8216a1a6558ccfd82bd9a54b9;laravel_session=eyJpdiI6IlQ0Tzhndno1S3VyZzNpYVZYQU40QlE9PSIsInZhbHVlIjoia3NnUXp0d3dsejJJYXo5Yk5FWjlLQ0FVY2ZVWDhnaEFzYnBUc2I1VDdcL0Rpc29qUFo0MFlub0dyaGs4YlBRYWI2RXlTNWZFendCVjlland6V3JqazhRPT0iLCJtYWMiOiJkYjZlYTg1NGU4N2FlZmE5ZDExODkzNmJkODY1YTVmNjQxZTkwMjNjYjNjMGExM2Y4NWQ3ZmFlNWRhZWNkNjk3In0%3D',
            'Host': 'pc-shop.xiaoe-tech.com',
            'Origin': 'http://pc-shop.xiaoe-tech.com',
            'Referer': 'http://pc-shop.xiaoe-tech.com/appzDSBtscz6568/video_details?id=v_5b0e8459e1ff5_nSu4umqK',
            'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest'
        }
```

**Comment by Yxnt** [comment]
这个应该不需要添加，我已经找小伙伴要账号去了

**Comment by redstoneleo** [comment]
也可以加我QQ 2281570025 ，我给你账号

**Comment by Yxnt** [comment]
已经增加音频下载，请看 1dde5421778e10b685a9cc6609c0ee0b1df307d8
