### ISSUE TITLE
resourceID and APPID？???

### ISSUE THREAD

**Issue by wrb233** [Yxnt/xiaoet#3]
是一回事吗？？？

**Comment by Yxnt** [comment]
我记得没错的话并不是，APPID是登陆后的第一个页面的URI，RESOURCEID是某个课程的ID

**Comment by wrb233** [comment]
好像不行了，是不是url的问题，我按照您的方法修改了四个变量，用安装好包的python环境运行xiaoet.py，结果什么错都没有报，就运行结束了

**Comment by Yxnt** [comment]
-.- 这就比较尴尬了。我晚上回去加个日志输出。 @wrb233

**Comment by Yxnt** [comment]
@wrb233 日志加了，最近比较忙每天加班到12点。

**Comment by wrb233** [comment]
@Yxnt 谢谢，注意休息，记得加鸡腿，节日快乐！！

**Comment by 1Boom** [comment]
@Yxnt 求救
Traceback (most recent call last):
  File "xiaoet.py", line 146, in <module>
    XET().download()
  File "xiaoet.py", line 142, in download
    self.video(url, media_dir, title, playurl)
  File "xiaoet.py", line 96, in video
    with open(m3u8_file, 'wb', encoding='utf8') as f:
ValueError: binary mode doesn't take an encoding argument

**Comment by Yxnt** [comment]
@1Boom 新开个issue然后把控制台的日志发上来我看看
