### ISSUE TITLE
@Yxnt 使用时报错

### ISSUE THREAD

**Issue by 1Boom** [Yxnt/xiaoet#4]
Traceback (most recent call last):
  File "xiaoet.py", line 146, in <module>
    XET().download()
  File "xiaoet.py", line 142, in download
    self.video(url, media_dir, title, playurl)
  File "xiaoet.py", line 96, in video
    with open(m3u8_file, 'wb', encoding='utf8') as f:
ValueError: binary mode doesn't take an encoding argument

**Comment by wrb233** [comment]
我这里也是不行，大神你有实测环境没有，小鹅通可能不定时更新它的内部机制，我抓到的ts片段全部都是加密的，这个不好搞啊，不像其他优酷腾讯爱奇艺

**Comment by 1Boom** [comment]
> 我这里也是不行，大神你有实测环境没有，小鹅通可能不定时更新它的内部机制，我抓到的ts片段全部都是加密的，这个不好搞啊，不像其他优酷腾讯爱奇艺

毕竟是专门做知识付费的，我这里用的是Win10 LTSB 2016，抓到的ts片段也是加密的，48.7-48.8M之后就无法抓取了，试了几次都是这样，然后就会出现上面那段报错的文字

**Comment by Yxnt** [comment]
@1Boom 能否麻烦把相关参数发送到j__xnt@163.com

**Comment by 1Boom** [comment]
> @1Boom 能否麻烦把相关参数发送到[j__xnt@163.com](mailto:j__xnt@163.com)

已发送至j__xnt@163.com

**Comment by Yxnt** [comment]
> > @1Boom 能否麻烦把相关参数发送到[j__xnt@163.com](mailto:j__xnt@163.com)
> 
> 已发送至[j__xnt@163.com](mailto:j__xnt@163.com)

有最新的信息么？应该是有参数过期了我这没办法获取到课程列表，我需要最新的参数去调试看看
