### ISSUE TITLE
怎么用ffmpg合并加密后的ts文件啊?

### ISSUE THREAD

**Issue by Toddwunz** [Yxnt/xiaoet#5]
你给的命令已经失效了,试着google了,但是各种报错
另外你的脚本里能加点注释么? 看不太懂,但真心好用
找到解决方法了:
ffmpeg -i "filename.m3u8" -c copy -bsf:a aac_adtstoasc "filename.mp4"

**Comment by Yxnt** [comment]
好的。多谢提醒，我补充下。

**Comment by Yxnt** [comment]
@Toddwunz 注释已增加至master
