### ISSUE TITLE
运行报错，求解感谢。

### ISSUE THREAD

**Issue by ghost** [Yxnt/xiaoet#7]
Traceback (most recent call last):
  File "xiaoet.py", line 168, in <module>
    XET().download()
  File "xiaoet.py", line 164, in download
    self.video(url, media_dir, title, playurl)
  File "xiaoet.py", line 115, in video
    with open(m3u8_file, 'wb', encoding='utf8') as f:
ValueError: binary mode doesn't take an encoding argument

**Comment by Toddwunz** [comment]
with open(m3u8_file, 'wb', encoding='utf8') as f:  
把wb改为w

**Comment by Yxnt** [comment]
看来小鹅通最近有改动。-。- 之前做这个脚本都是帮小伙伴弄的。

**Comment by ghost** [comment]
> 看来小鹅通最近有改动。-。- 之前做这个脚本都是帮小伙伴弄的。

最后说用Mac上Downie下载的

**Comment by Yxnt** [comment]
> > 看来小鹅通最近有改动。-。- 之前做这个脚本都是帮小伙伴弄的。
> 
> 最后说用Mac上Downie下载的

-。-好吧，那我关闭了这个issue了
